name: Build iNav MATEKH743

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "boards/**"
      - "cmake/**"
      - "scripts/**"
      - ".github/workflows/build-matekh743.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout repository
      # -------------------------------
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      # -------------------------------
      # Install required build tools
      # -------------------------------
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            python3 \
            git

      # -------------------------------
      # Debug: List targets
      # -------------------------------
      - name: Debug: List all targets
        run: |
          echo "Available iNav targets:"
          ls -R src/main/target

      # -------------------------------
      # Build firmware (native mode, no Docker)
      # -------------------------------
      - name: Build MATEKH743 (native)
        run: |
          chmod +x build.sh
          ./build.sh -n MATEKH743

      # -------------------------------
      # Upload output firmware as artifact
      # -------------------------------
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: inav_MATEKH743_firmware
          path: build/MATEKH743/**
